# Generated by Django 6.0.6 on 2026-06-04 20:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acudiente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Coordinador',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('nivel', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PeriodoAcademico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('rol', models.CharField(choices=[('acudiente', 'Acudiente'), ('docente', 'Docente'), ('coordinador', 'Coordinador'), ('estudiante', 'Estudiante')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActividadEvaluativa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('publicada', 'Publicada'), ('cerrada', 'Cerrada')], default='borrador', max_length=20)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='polls.asignatura')),
                ('periodo_academico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='polls.periodoacademico')),
                ('publicado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades_publicadas', to='polls.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='asignatura',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas', to='polls.curso'),
        ),
        migrations.AddField(
            model_name='curso',
            name='docente_titular',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos_titular', to='polls.docente'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='docente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaturas', to='polls.docente'),
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('es_repitente', models.BooleanField(default=False)),
                ('tiene_condicion_especial', models.BooleanField(default=False)),
                ('descripcion_condicion', models.TextField(blank=True, null=True)),
                ('riesgo', models.CharField(blank=True, choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto')], max_length=10, null=True)),
                ('acudiente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiantes', to='polls.acudiente')),
                ('curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiantes', to='polls.curso')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estudiante', to='polls.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='AlertaAcademica',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('es_automatica', models.BooleanField(default=False)),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('indicador_tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('indicador_valor_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('indicador_valor_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('generada_en', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='polls.estudiante')),
                ('generada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_generadas', to='polls.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='grado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='polls.grado'),
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asunto', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('enviado_en', models.DateTimeField(auto_now_add=True)),
                ('mensaje_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas', to='polls.mensaje')),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to='polls.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asunto', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('enviada_en', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to='polls.coordinador')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroAsistencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('cerrado', models.BooleanField(default=False)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_asistencia', to='polls.curso')),
            ],
            options={
                'unique_together': {('curso', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='Observacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('academica', 'Académica'), ('convivencia', 'Convivencia'), ('asistencia', 'Asistencia'), ('otro', 'Otro')], max_length=20)),
                ('descripcion', models.TextField()),
                ('es_positiva', models.BooleanField(default=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='polls.estudiante')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observaciones_registradas', to='polls.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='docente',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='docente', to='polls.usuario'),
        ),
        migrations.CreateModel(
            name='DetalleAsistencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('presente', 'Presente'), ('ausente', 'Ausente'), ('tardanza', 'Tardanza'), ('justificado', 'Justificado')], max_length=20)),
                ('motivo_justificacion', models.TextField(blank=True, null=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='polls.estudiante')),
                ('registro_asistencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='polls.registroasistencia')),
                ('modificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias_modificadas', to='polls.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='coordinador',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coordinador', to='polls.usuario'),
        ),
        migrations.AddField(
            model_name='acudiente',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acudiente', to='polls.usuario'),
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('actividad_evaluativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='polls.actividadevaluativa')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='polls.estudiante')),
            ],
            options={
                'unique_together': {('actividad_evaluativa', 'estudiante')},
            },
        ),
        migrations.CreateModel(
            name='NotificacionLectura',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('leido_en', models.DateTimeField(auto_now_add=True)),
                ('notificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='polls.notificacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_leidas', to='polls.usuario')),
            ],
            options={
                'unique_together': {('notificacion', 'usuario')},
            },
        ),
        migrations.CreateModel(
            name='DestinatarioMensaje',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('leido', models.BooleanField(default=False)),
                ('leido_en', models.DateTimeField(blank=True, null=True)),
                ('mensaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatarios', to='polls.mensaje')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_recibidos', to='polls.usuario')),
            ],
            options={
                'unique_together': {('mensaje', 'destinatario')},
            },
        ),
        migrations.CreateModel(
            name='AlertaLectura',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('leido_en', models.DateTimeField(auto_now_add=True)),
                ('alerta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='polls.alertaacademica')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_leidas', to='polls.usuario')),
            ],
            options={
                'unique_together': {('alerta', 'usuario')},
            },
        ),
    ]
